GET {{baseUrl}}api/cities?page=1&limit=10&search=&state=68735f893f3a855714bcb377&country=68735f593f3a855714bc983d HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}
