PUT {{baseUrl}}auth/cities/68133cf3063880871694de59 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "state": "681325ec585939af076c5d70",
  "name": "Udaipur",
  "status": true
}